// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace ProductManage.Models;

/// <summary>
/// Products sold or used in the manfacturing of sold products.
/// </summary>
public partial class Product
{
    /// <summary>
    /// Primary key for Product records.
    /// </summary>
    [DisplayName("流水號")]
    public int ProductId { get; set; }

    /// <summary>
    /// Name of the product.
    /// </summary>
    [DisplayName("產品名稱")]
    public string Name { get; set; }

    /// <summary>
    /// Unique product identification number.
    /// </summary>
    [DisplayName("產品號碼")]
    public string ProductNumber { get; set; }

    /// <summary>
    /// Product color.
    /// </summary>
    [DisplayName("顏色")]
    public string Color { get; set; }

    /// <summary>
    /// Standard cost of the product.
    /// </summary>
    [DisplayName("原定價")]
    public decimal StandardCost { get; set; }

    /// <summary>
    /// Selling price.
    /// </summary>
    [DisplayName("銷售價格")]
    public decimal ListPrice { get; set; }

    /// <summary>
    /// Product size.
    /// </summary>
    [DisplayName("尺寸")]
    public string Size { get; set; }

    /// <summary>
    /// Product weight.
    /// </summary>
    [DisplayName("重量")]
    public decimal? Weight { get; set; }

    /// <summary>
    /// Product is a member of this product category. Foreign key to ProductCategory.ProductCategoryID. 
    /// </summary>
    public int? ProductCategoryId { get; set; }

    /// <summary>
    /// Product is a member of this product model. Foreign key to ProductModel.ProductModelID.
    /// </summary>
    public int? ProductModelId { get; set; }

    /// <summary>
    /// Date the product was available for sale.
    /// </summary>
    public DateTime SellStartDate { get; set; }

    /// <summary>
    /// Date the product was no longer available for sale.
    /// </summary>
    public DateTime? SellEndDate { get; set; }

    /// <summary>
    /// Date the product was discontinued.
    /// </summary>
    public DateTime? DiscontinuedDate { get; set; }

    /// <summary>
    /// Small image of the product.
    /// </summary>
    public byte[] ThumbNailPhoto { get; set; }

    /// <summary>
    /// Small image file name.
    /// </summary>
    public string ThumbnailPhotoFileName { get; set; }

    /// <summary>
    /// ROWGUIDCOL number uniquely identifying the record. Used to support a merge replication sample.
    /// </summary>
    public Guid Rowguid { get; set; }

    /// <summary>
    /// Date and time the record was last updated.
    /// </summary>
    [DisplayName("最後修改時間")]
    public DateTime ModifiedDate { get; set; }

    public virtual ProductCategory ProductCategory { get; set; }

    public virtual ProductModel ProductModel { get; set; }

    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; } = new List<SalesOrderDetail>();
}