// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProductManage.Models;

public partial class VGetAllCategory
{
    public string ParentProductCategoryName { get; set; }

    public string ProductCategoryName { get; set; }

    public int? ProductCategoryId { get; set; }
}